version: '3'

services:
  redis:
    image: redis:latest
    container_name: dev_redis
    environment:
      VOLUMES_DIR: ${VOLUMES_DIR}
    volumes:
      - '~/${VOLUMES_DIR}/redis-data:/data'
    ports:
      - "127.0.0.1:6377:6379"
    restart: unless-stopped

  db:
    container_name: dev_database
    image: postgres:16.2-alpine
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      VOLUMES_DIR: ${VOLUMES_DIR}
    volumes:
      - "~/${VOLUMES_DIR}/pg-data:/var/lib/postgresql/data"
      - "~/${VOLUMES_DIR}/backups:/backups"
    ports:
      - "5435:5432"
