version: '3'

services:
  db:
    container_name: database
    image: postgres:16.2-alpine
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      VOLUMES_DIR: ${VOLUMES_DIR}
    volumes:
      - "~/${VOLUMES_DIR}/pg-data:/var/lib/postgresql/data"
      - "~/${VOLUMES_DIR}/backups:/backups"
    ports:
      - "5432:5432"


  db_migration:
    container_name: database_migration
    build:
      context: .
    restart: "on-failure"
    depends_on:
      - db
    env_file: .env
    command: sh -c "python -m alembic upgrade head"

  redis:
    image: redis:latest
    container_name: bot_redis
    environment:
      VOLUMES_DIR: ${VOLUMES_DIR}
    volumes:
      - '~/${VOLUMES_DIR}/redis-data:/data'
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped


  bot:
    container_name: helper_bot
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    restart: "unless-stopped"
    env_file: .env
    ports:
      - "4443:4443"
