version: "3"

services:
  db:
    container_name: database
    image: postgres:16.2-alpine
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      VOLUMES_DIR: ${VOLUMES_DIR}
    volumes:
      - "~/${VOLUMES_DIR}/pg-data:/var/lib/postgresql/data"
      - "~/${VOLUMES_DIR}/backups:/backups"
    ports:
      - "5432:5432"
#  db_migration:
#    container_name: database_migration
#    build:
#      context: .
#    restart: "on-failure"
#    depends_on:
#      - db
#    env_file: .env
#    command: sh -c "python -m migrations upgrade head"
#    bot:
#        container_name: tgbot
#        build:
#            context: .
#        stop_signal: SIGINT
#        restart: "unless-stopped"
#        env_file: .env
#        depends_on:
#            - db
#            - db_migration
#            - redis